sudo: false
git:
  depth: 1
language: node_js
node_js: node
after_script:
  - npm install istanbul-coveralls
  - npm run-script coverage
  - node node_modules/.bin/istanbul-coveralls
notifications:
  email: false
